/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "auth": {
            "failedRefreshToken": string;
            "failedTokens": string;
            "login": string;
            "notFound": string;
            "unauthorized": {
                "notVerified": string;
                "refreshToken": string;
            };
        };
    };
    "response": {
        "auth": {
            "admin": string;
            "login": string;
            "logout": string;
            "refreshTokens": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
