/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "auth": {
            "failedRefreshToken": string;
            "failedTokens": string;
            "login": string;
            "notFound": string;
            "unauthorized": {
                "notVerified": string;
                "refreshToken": string;
            };
        };
    };
    "response": {
        "auth": {
            "admin": string;
            "login": string;
            "logout": string;
            "refreshTokens": string;
        };
    };
    "validation": {
        "admin": {
            "firstName": {
                "isString": string;
                "minLength": string;
                "maxLength": string;
            };
            "lastName": {
                "isString": string;
                "minLength": string;
                "maxLength": string;
            };
            "email": {
                "required": string;
                "invalid": string;
            };
            "password": {
                "isString": string;
                "minLength": string;
                "maxLength": string;
            };
            "role": string;
            "refreshToken": {
                "isString": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
