export const APPOINTMENTS_CONFIG = {
  response: {
    error: {
      apposSearch: 'Búsqueda sin resultados',
      apposSearchError: 'Error al buscar turnos',
      apposStatistics: 'Error al obtener estadísticas de turnos',
      daysWithAppos: 'Error al obtener dias con turnos',
      errorFoundPlural: 'Error al buscar turnos',
      invalidId: 'ID de turno inválido',
      invalidSearchType: 'Tipo de búsqueda no valido',
      notCount: 'Error al contar turnos',
      notCreated: 'Turno no creado. Ocurrió un error inesperado al momento de crear el turno. Inténtalo nuevamente',
      notFoundMonths: 'Error al buscar los distintos meses de turnos',
      notFoundPlural: 'Búsqueda de turnos sin resultados',
      notFoundPluralFilterAll: 'Error en la búsqueda de turnos por profesional y año',
      notFoundPluralFilterNone: 'Error en la búsqueda de turnos sin filtros',
      notFoundPluralFilterProfessional: 'Error en la búsqueda de turnos por profesional',
      notFoundPluralFilterYear: 'Error en la búsqueda de turnos por año',
      notFoundSingular: 'Turno no encontrado',
      notFoundUniqueProfessionals: 'Error al buscar profesionales únicos',
      notFoundYears: 'Error al buscar los distintos años de turnos',
      notRemoved: 'Turno no eliminado. Ocurrido un error inesperado al momento de eliminar el turno. Inténtalo nuevamente',
      notUpdated: 'Turno no actualizado',
    },
    success: {
      apposStatistics: 'Estadísticas de turnos',
      count: 'Total de turnos contados',
      created: 'Turno creado',
      daysWithAppos: 'Días con turnos',
      empty: 'El paciente aún no posee turnos',
      emptyDatabase: 'No se encontraron turnos',
      emptyDaysWithAppos: 'No se encontraron días con turnos',
      emptyMonths: 'No se encontraron los distintos meses de turnos',
      emptyUniqueProfessionals: 'No se encontraron profesionales únicos',
      emptyYears: 'No se encontraron los distintos años de turnos',

      emptyFoundPluralFilterAll: 'No se encontraron turnos por profesional y año',
      emptyFoundPluralFilterNone: 'No se encontraron turnos',
      emptyFoundPluralFilterProfessional: 'No se encontraron turnos por profesional',
      emptyFoundPluralFilterYear: 'No se encontraron turnos por año',

      foundMonths: 'Se encontraron los distintos meses de turnos',
      foundPlural: 'Turnos encontrados',
      foundSingular: 'Turno encontrado',
      foundUniqueProfessionals: 'Se encontraron los profesionales únicos',
      foundYears: 'Se encontraron los distintos años de turnos',
      removed: 'Turno eliminado',
      updated: 'Turno actualizado',
    },
  },
};
